### ISSUE TITLE
Enum for Syntax

### ISSUE THREAD

**Issue by mre** [trishume/syntect#226]
Right now I'm using the following method to define the syntax highlighting:

```rust
use syntect::parsing::SyntaxSetBuilder;
let mut builder = SyntaxSetBuilder::new();
let ss = builder.build();
self.syntax_set.find_syntax_by_token("ruby");
```

This is nice, but typos could lead to confusing results:

```rust
self.syntax_set.find_syntax_by_token("ruyb");
```

I wonder if there is a way to define the syntax as an enum value like this:

```rust
self.syntax_set.set_syntax(Syntax::Ruby);
```

The advantage would be, that typos directly lead to compile-time errors and that code-completion could provide syntax suggestions based on the user input .
Maybe we could generate this enum of possible syntax values from the Sublime Text syntax definitions?

**Comment by trishume** [comment]
This only seems really useful for when you're highlighting only one or two specific languages, which is pretty rare among syntect users I think. Especially since even then it'll only work for built in languages and not for any you add yourself.

I think the total time it'll take to implement, document and review this feature would eclipse the total time saved by syntect users doing specific-language highlighting making typos and then taking slightly longer to diagnose the immediate runtime error instead of compile error.

**Comment by trishume** [comment]
Thanks for the suggestion though, I'm generally in favour of using enums to provide compile-time guarantees. I just don't think it's worth the effort in this case given the benefit it would provide, how people tend to use syntect and syntect's underlying dynamic nature.

**Comment by mre** [comment]
Makes sense. For [prettyprint](https://github.com/mre/prettyprint), I might end up defining a custom little enum with a few key languages to allow for compile-time-safety while also supporting a fallback for strings. This way, we should get the best of both worlds. 😃 
Thanks for the response.
