### ISSUE TITLE
Always skipping the last symbol in a line

### ISSUE THREAD

**Issue by terhechte** [trishume/syntect#234]
Hey! I'm using syntect to generate HTML with classes (instead of colors) for code. I.e. instead of having `<span color="red">let</span>` I'm trying to have `<span class="storage keyword">let</span>`. This works reasonably well, but for some languages (so far it happened with `R` and `Swift`, but I guess there're more) it will print partial code. Here's my (simplified) implementation with some R code:

``` Rust
use syntect::html::{tokens_to_classed_html, ClassStyle};
use syntect::parsing::{ParseState, SyntaxSet};

fn main() {
    let current_code = r#"
x <- 5
y <- 6
x + y
x + y
"#.to_string();
    let syntax_set = SyntaxSet::load_defaults_newlines();

    let syntax = syntax_set.find_syntax_by_name("R").unwrap();

    let mut ps = ParseState::new(&syntax);
    let mut html_str = String::new();
    for line in current_code.lines() {
        let parsed_line = ps.parse_line(line, &syntax_set);
        html_str.push_str(
            &tokens_to_classed_html(
                line,
                parsed_line.as_slice(),
                ClassStyle::Spaced)
            .as_str(),
            );
        html_str.push('\n');
    }
    println!("output:\n{}", &html_str);
}
```

The output looks like this:
```
output:
<span class="source r">
x <span class="keyword operator assignment r">&lt;-</span> <span class="constant numeric float decimal r">5</span>
y <span class="keyword operator assignment r">&lt;-</span> <span class="constant numeric float decimal r">6</span>
x <span class="keyword operator arithmetic r">+</span>
x <span class="keyword operator arithmetic r">+</span>
```

As you can see the `y` is missing in the `x + y` lines, and the original `span` (from `<span class="source r">` is never closed.

Am I doing something wrong here?

**Comment by trishume** [comment]
Nope seems I just implemented `tokens_to_classed_html` wrong. The bug is that the implementation of `tokens_to_classed_html` doesn't print the remaining part of the string if there's no operator at the end of the line.

The thing about the spans never being closed is a different problem that will require deprecating the current function and adding a new API that can keep track of unclosed spans to close at the end.

You do have one bug in your code which is that you're using the `newlines` version of the syntaxes but feeding it lines without newlines at the end. Try using the `syntect::util::LinesWithEndings` iterator in your loop instead of `.lines()`.

I might find time to fix this this week but not sure. Feel free to PR if you want, it isn't too hard to fix. Just change `tokens_to_classed_html` to print the escaped remainder from `cur_index` to the end. Then create a struct like `ClassedHtmlGenerator` that has a single `usize` that's the number of open `spans`, put the function as a method on that struct like `html_for_line` and have it keep track of the number of open spans, then add another method like `finalize() -> String` that just gives back the necessary number of close span tags.

**Comment by terhechte** [comment]
Thanks! I gave it a try here:
https://github.com/trishume/syntect/pull/235
