### ISSUE TITLE
Named color/style

### ISSUE THREAD

**Issue by ratmice** [trishume/syntect#252]
As far as I can tell, the easy::HighlightLines and friends all (through Style) return a Color containing rgba components. Having looked around through the examples and the html parser
I was not able to find a place where highlighting occurs over a string of code except defers
 coloring to some later phase which binds the (name or a unique id) to the rgba components extracted from the theme.

If I understand correctly, because the theme also contributes FontStyle, etc the correct way to implement highlighting once/apply a theme map is via a ScopeRegionIterator, which then converts the theme's semantic names into both a FontStyle/Color map?

I'm not actually parsing to CSS but it would seem like basically the same idea.
Any pointers in the right direction would be appreciated.

**Comment by trishume** [comment]
I'm not sure I'm parsing exactly what you're asking, but I think I get it. An easy utility for parsing into coarse semantic categories based on scope selectors without using full color themes is a weakness in the current API.

There are a few ways to do it:
- Use the trick where you make a `tmTheme` with specially coded color values for the different categories. This approach is the easiest and will perform the best (barring some effort) but might make you feel bad, I give you permission not to feel bad doing this.
- Use the `parsing` module APIs to get tokenization at the scope stack level. This will give you a very detailed rich semantic representation of the code which you can match on with selectors. See the `synstats` example. The thing is you won't get the optimized way of matching multiple selectors that the built in highlighting code uses. If you want to use this approach with many selectors with maximum performance you can look at the `highlighting` module code, which uses the public `parsing` APIs so can be replicated out of crate, and replicate some of how it matches selectors.

**Comment by ratmice** [comment]
Thanks, this basically answers my question, I'm going to try the second option first,
as it seems to more naturally handle bold/italic/underline, than the first,
If i can come up with something which seems to fit in the easy:: module will make a pull request.
Feel free to close or keep open at you preference

**Comment by terhechte** [comment]
@ratmice I'm not sure if it is help. I ran into a similar issue where I wanted to have color names / tokens instead of RGBA values as I am using syntect to generate HTML that should look correct in dark and light mode CSS themes. If the HTML contains raw color values, it will look out of place in one of the two modes. 

This PR introduces the functions to generate color names instead of color values:
https://github.com/trishume/syntect/pull/235

I do have a small script here that parses TextMate themes and returns CSS files that map from the tokens generated in the PR above to the theme color value. So, you can parse two different text-mate themes (solarized and solarized-dark) and generate two different CSS files, one for dark, one for light. Finally, the highlighter code, generated by the PR above, will work with both themes. 

If that's useful to you, I can open source that script.

**Comment by chrisvittal** [comment]
Hey @terhechte I'm also looking for a way to handle css `prefers-color-scheme` media selectors. I'd love it you can share that script. Thanks!

**Comment by uwearzt** [comment]
@terhechte i would also be interested in the script. I would like to try dark/light modes for my website.

**Comment by Enselic** [comment]
Closing since this was more of a question that is now resolved rather than something to keep open as an issue

**Comment by terhechte** [comment]
As it happens, I completely forgot about this. @uwearzt @chrisvittal I've open sourced the code to generate CSS and to generate highlighted HTML based on this CSS here:

https://github.com/terhechte/syntectcss
