### ISSUE TITLE
Consider decoupling html and assets?

### ISSUE THREAD

**Issue by tmpfs** [trishume/syntect#299]
Hi, thanks for syntect I have just finished integrating it with my program and it is working nicely :+1: 

I thought I would do some fine-tuning to reduce the binary file size as I am loading custom syntax definition bundles I wanted to remove the `assets` feature but I am using `html` to output HTML and noticed that it depends on `assets`.

So it appears that when using `html` I am unable to prevent syntect from bundling the default syntax definitions, is that correct? 

Would it be easy/possible to decouple these features?

Thanks!

**Comment by keith-hall** [comment]
I just tried changing the `html` feature in [Cargo.toml](https://github.com/trishume/syntect/blob/26854821c73578dd25d368eefdf8b9e56c1ea397/Cargo.toml#L67) to `html = ["parsing"]` instead of `html = ["parsing", "assets"]` and tried building with ` cargo build --no-default-features --features "parsing html yaml-load dump-load dump-create regex-fancy"` (i.e. same as `default-fancy` but without `assets`) and it seemed to work okay. I didn't see anything in the `html.rs` or `lib.rs` modules that makes it depend on the `assets` feature, but I'm far from a Rust expert, so maybe I'm missing something, but it seems like a safe change to make?

**Comment by trishume** [comment]
Yup it definitely seems like html shouldn't depend on `assets` and if there is a dependency it should be easy to fix.

I think the only actual dependency is the tests, so this just needs a 2 line change to fix: remove the dependency in the `Cargo.toml` file, and change the `cfg` line above the `html.rs` tests to not include the tests if the assets feature isn't present (I think there might be other tests that do this).

I'm pretty bad at getting around to things like this in a reasonable amount of time unless somebody submits a PR, so I encourage you to do so if you want, and otherwise you can use a fork with a git dependency with just the `Cargo.toml` change.

**Comment by tmpfs** [comment]
Thanks for looking into this @keith-hall and thanks for the PR. I just pulled your branch and ran the tests and all seems good, now I am going to point to that quickly and see whether I can slim my binary a bit :+1:

**Comment by tmpfs** [comment]
This has shaved off exactly 384384 bytes which is a little bit more than I anticipated! :+1: 

@trishume, could I trouble you to publish this as a `4.2.1` patch release?

Thanks very much!

**Comment by trishume** [comment]
I released `v4.3.0` with this change. Thanks for the report and thanks @keith-hall for the fix!

**Comment by tmpfs** [comment]
That is awesome, thanks very much to you both :clap:
