### ISSUE TITLE
Incorrect Python Comments Color Highlighting

### ISSUE THREAD

**Issue by mitnk** [trishume/syntect#303]
Python Code like this,
```python
def foo():
    pass

# comments in middle will make normal code gray too
def bar():
    pass
```

will be rendered like this:
![image](https://user-images.githubusercontent.com/177049/90124302-bcc1c280-dd92-11ea-8822-d16e1fcd685c.png)

Using Python syntax:
```rust
...
let syntax = syntax_set.find_syntax_by_name("Python").unwrap();
...
```

**Comment by keith-hall** [comment]
This is using `load_default_newlines`? Can you share a minimum reproducible example implementation code please? Afaik, the examples provided like `syncat` and `synhtml` are working correctly...

**Comment by mitnk** [comment]
@keith-hall Here is a minimum code to reproduce it:
```rust
use syntect::html::ClassedHTMLGenerator;
use syntect::parsing::SyntaxSet;

fn main() {
    let code = "// one line comment\nvoid main() { }\n";

    let syntax_set = SyntaxSet::load_defaults_newlines();
    let syntax = syntax_set.find_syntax_by_name("C").unwrap();

    let mut html_generator = ClassedHTMLGenerator::new(&syntax, &syntax_set);
    for line in code.lines() {
        html_generator.parse_html_for_line(&line);
    }
    let html = html_generator.finalize();

    println!("html: {:?}", html);
}
```

In `html`, you can see, the code line (i.e. `void main() { }`) are compiled into the `comment <span>`. This issue happens in `C`, `Python`, but not `Rust`.

Since `ClassedHTMLGenerator` just deprecated in latest version of syntect, I will try using the new way to see if the issue still exists (may not related).

**Comment by trishume** [comment]
@mitnk yah this is a common problem the docs warn about but it's easy to miss it and there's not much to indicate what's going wrong other than weird highlighting. All you need to do is either switch to `SyntaxSet::load_defaults_nonewlines()` or better yet use the iteration method used in the examples rather than `.lines()`, because `.lines()` doesn't include the newlines.

I might try and think of some way to warn or error if you provide the wrong type of lines, but it's made somewhat tricky by it being potentially okay for the last line to not have a newline after it even in the `_newlines` mode.

**Comment by mitnk** [comment]
The [example uses](https://docs.rs/syntect/4.3.0/syntect/html/struct.ClassedHTMLGenerator.html#example) `.lines()` on string and uses `load_defaults_newlines()` instead of `load_defaults_nonewlines()`. Does that mean the example need to be updated to use `load_defaults_nonewlines()`?

**Comment by keith-hall** [comment]
I believe it should be updated, yes. [Probably also the `synhtml-css-classes` example](https://github.com/trishume/syntect/blob/f444f604f6b96f5f6c17cb63a84f891f69516586/examples/synhtml-css-classes.rs#L46)

**Comment by mitnk** [comment]
Thanks for you replies and this project!
