### ISSUE TITLE
Support 16 color terminal printing

### ISSUE THREAD

**Issue by sidju** [trishume/syntect#309]
I am currently writing [hired](https://github.com/sidju/hired) my own bastardization of 'ed', the classic command line text editor. In this endeavor I have of course used this library for the highlighting, but I have some issues with integrating it with my current UI rewrite. As such I have some requests (which I could help implement, of course).

In essence, I want 16 color support in the terminal. I realize that this is not compatible with neither the theme file format nor the current Color struct, so this might end up being a bit tricky.

Anyways, I have some ideas:
 1. If one separates the parsing into fields from the theming of the fields, instead marking the scopes. This is probably not worth the complications it brings, though, since it is a very deep change.
 1. Allow 16 color in the Color struct. With this I could put together my own theme inside the application and run along.
 1. Add a conversion from Color to 16 color, allowing use of existing theme files but risking confusion for users. This could be added similarly to the util::as_24_bit_terminal_escaped function.

Essentially, what would you prefer? I will work on it until I have a solution for me, but if I can make it a PR that would be better.

**Comment by trishume** [comment]
This is something `bat` has also ran into, there I recommended an approach where they use an alpha of zero (transparent, so otherwise useless) to signify that the red value of the color should be interpreted as a terminal color. It's kind of a hack but it allows easy re-use of the TextMate theme format and all the optimizations I implemented for applying those themes. See https://github.com/sharkdp/bat/pull/543

Another alternative is that all the APIs that the highlighting uses are public so you could re-implement your own simple highlighting using similar logic to syntect's highlighting module except with less features and a custom theme data structure supporting terminal colors, probably copy-pasting heavily from syntect.

I think I'd probably accept a PR for a helper function like `as_24_bit_terminal_escaped` that did the logic of checking the alpha value and using terminal colors in the exact same way as `bat`, so that themes made for bat would be compatible and maybe `bat` would even switch to using it.

**Comment by sidju** [comment]
"Nice" hack with the alpha value. I have implemented using this and the vector you get out from the highlighter.

However, my code uses uses crossterm. Should I make a PR with a feature flag for 'terminal-printing' (so that users of it as a library don't drag in the additional dependencies) or should I just link my code here for future searchers and call it a day?

**Comment by trishume** [comment]
Given that there's a whole bunch of different terminal color output libraries, probably better to just link the code here, it's not that hard to reimplement with whatever library people are using.

**Comment by sidju** [comment]
Then, in essence, [here](https://github.com/sidju/hired/blob/9ee8dc1bf29d5410417867d86518603da30317a1/src/ui/mod.rs#L1)

In the beginning of the file are some helpers for converting from the syntect internal data-structures. The big public function is the printing logic with some additional features, such as line numbers and wrapping.

Thank you very much for your advice and help!
