### ISSUE TITLE
Panic in regex parser

### ISSUE THREAD

**Issue by epage** [trishume/syntect#334]
The [CI for my project reported the following](https://github.com/cobalt-org/cobalt.rs/pull/854#issuecomment-835467115)
```
---- syntax_highlight::syntect::test::markdown_renders_rust stdout ----
thread 'syntax_highlight::syntect::test::markdown_renders_rust' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.5.0/src/parsing/regex.rs:74:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    syntax_highlight::syntect::test::markdown_renders_rust
```
That corresponds with the unwrap from
```
            let regex =
                regex_impl::Regex::new(&self.regex_str).expect("regex string should be pre-tested");
            self.regex.fill(regex).ok();
            self.regex.borrow().unwrap()
```

I can't reproduce locally; I'm assuming this is some kind of race, which suggests AtomicLazyCell is not actually threadsafe.  

Both locally and the PR in question are using syntect 4.5.0.  `lazycell` is set to 1.3.0 in my lock file which is the latest version.

**Comment by trishume** [comment]
Ouch yah, sorry for the delayed reply. Things I'm thinking of:

- That `.ok()` is a weird way to ignore the error from if the cell is already full, but it should be fine to drop it.
- This looks like a bug in `lazycell`. I wondered if they aren't using the right ordering parameters on their atomic operations, and this only causes a problem when the compiler does some optimization based on that. I checked the code and I'm not sure whether it's right or not, the orderings on the lock atomics are right but I haven't researched the semantics of how they're ordered with other memory operations and how UnsafeCell works, it's plausible that the code is wrong.

**Comment by rhysd** [comment]
I may figure out the reason. Let's say there are 2 threads trying to fill the `self.regex` lazy cell.

1. Thread1 starts `.fill()` call and acquires lock
2. Thread2 starts `.fill()` call but cannot acquires lock (since Thread1 already did it)
3. `.fill()` in Thread2 returns `Err(value)` (but Thread2 ignores it by `.ok()`)
4. Thread2 calls `.borrow()`. However, at this point, the `.fill()` call in Thread1 is not completed yet. So `.borrow()` in Thread2 returns `None`
5. The `.unwrap()` crashes
6. Thread1 finishes to set value at `.fill()`

So,

```rust
cell.fill(something).ok();
cell.borrow().unwrap();
```

is not crash-free.

**Comment by rhysd** [comment]
I'll try to make a PR to fix this tomorrow (it's 2am in Japan and I'm too sleepy now).
