### ISSUE TITLE
Syntax overlay: ability to augment existing syntax

### ISSUE THREAD

**Issue by AmokHuginnsson** [trishume/syntect#395]
Hello, thank you for this very useful project.

I use it indirectly through `bat`.

One thing that is missing in *sublime text editor* syntax highlighting scheme is the ability to **easily** and **cheaply** augment/enhance existing syntax definitions.

Concrete example follows:

In every programming language I use I follow very specific coding/formatting convention, i.e. I format class data members, function arguments and global variables according to following rules: `_dataMember`, `functionArgument_` and `_globalVariable_`.

This formatting is easily distinguishable at the very first glance and greatly improves code in readability department (at least for me).
 
In virtually every programming environment/text editor that I have tried that supports syntax highlighting at all (vim, emacs, Visual Studio, Eclipse, gedit(gtksourceview), KDevelop) it is quite trivial to enhance existing highlighting capability in such a way that I can add custom and specific highlighting rules in such a way that I can have *data members*, *function arguments* and *global variables* highlighted in different colors of my choosing.

Unfortunately *sublime text editor* syntax highlighting scheme does not directly provide such capability. The only way to achieve desired effect is to completely overwrite existing syntax, which can be cumbersome.

Would it be possible to enhance **syntect** library in such a way to allow either expanding existing syntax definitions directly, or allow use of two syntaxes at once, one normal syntax for given file and one (or more) overlay syntax that would allow small highlighting enhancement/customization over existing one?

**Comment by keith-hall** [comment]
Thanks for the feedback and request.

Using two syntax definitions together seems like out of scope to me - Sublime Text itself doesn't support it, and it would get very complicated and would only be used for this specific use case. Sublime Text doesn't really support LSP semantic highlighting either as I understand, which could potentially also be used to cater for this use case [if it did/in other editors]. But it may be possible to somehow integrate `bat` with LSP if so desired?

I would personally think a more realistic solution would be one of the following:
- use `syntect` to parse the `sublime-syntax` file and augment it so that whenever a `variable` scope is encountered, it would apply a regex to scope it differently depending on whether the token starts and/or ends with an underscore character. This could be quite hard to get right for all syntaxes, but would save needing to manually "completely overwrite the existing syntax". (Even using Sublime Text's `extends` functionality would take some thought/time for each syntax definition I believe.) The color scheme could then use these more precise scopes to color each distinctly.
- provide a wrapper around the `syntect` library to do this work while highlighting, without the need for modifying the syntax definitions themselves - `syntect` already exposes everything you'd need to achieve this. Presumably you'd need to recompile `bat` to use the wrapper, which might be a maintenance burden. Technically `bat` could be augmented to do this directly if the maintainers are interested to add this type of scope based further regex matching/rescoping.
- do it in a wrapper script after `bat` has applied the syntax highlighting. This may be the least invasive solution but also hard to get right due to `bat` outputting the grid, and the text wrapping to terminal width etc.

**Comment by Enselic** [comment]
The alternative approaches proposed by keith-hall seems like more realistic approaches, so I'll go ahead and close this issue now. Thanks anyway for taking the time to make a feature request.
