### ISSUE TITLE
4.7 is not uploaded to crates.io

### ISSUE THREAD

**Issue by rhysd** [trishume/syntect#428]
Hi,

I'm very interested in v4.7 changes described in [the changelog](https://github.com/trishume/syntect/blob/master/CHANGELOG.md). However the latest version uploaded to crates.io is [v4.6.0](https://crates.io/crates/syntect/versions).

I think there were some problems on the latest version since they were once uploaded then unpublished. Is there a plan to publish a new version for v4.7?

**Comment by Enselic** [comment]
The lazy-loading of syntaxes changed the binary format of assets, which constitutes a semver breaking change. So the next release will be 5.0.0. Since we had to do a major bump, we wanted to take the opportunity to adjust the API a bit. The only thing left do do is solving https://github.com/trishume/syntect/issues/98 which is done in multiple increments, and there is an open PR awaiting review, but it is not the final PR

The best way to follow progress is subscribing to https://github.com/trishume/syntect/pull/409 (which will be updated before 5.0.0)

**Comment by rhysd** [comment]
Thank you so much for sharing the situation. I understood and will watch the progress.

**Comment by Enselic** [comment]
Hi rhysd-san, just wanted to ping you about that 5.0.0 has been published on crates.io now since a few days back, in case you didn't notice: https://github.com/trishume/syntect/releases/tag/v5.0.0

**Comment by rhysd** [comment]
@Enselic Thank you for the notification. And congrats on the new major version! I'll try it soon.
