### ISSUE TITLE
Funding Syntect features that enable new syntax definitions (TypeScript etc.)?

### ISSUE THREAD

**Issue by rauschma** [trishume/syntect#473]
AFAICT, the following two issues currently prevent Syntect from being able to use new Sublime syntax definitions (such as the one for TypeScript):

* https://github.com/trishume/syntect/issues/271
* https://github.com/trishume/syntect/issues/323

Would funding help with fixing these issues? How much money would it be?

Context: I’m writing a Markdown-based book generator in Rust (to be open sourced eventually) and I’d like to use Sublime’s new syntax definitions.

**Comment by keith-hall** [comment]
Hi, great question! I would find it hard to even estimate how long it would take to add support for these latest features, as so many things will need to change/be refactored etc. The whole API will look different, as it can no longer return a list of scope operations per line due to the ability to backtrack up to 500 lines for the branch points etc. And I'm pretty sure it is going to need to return the "scoped tokens" instead of scope operations, lots of complexity already comes from how it applies meta scopes etc. which make it hard to support the `pop: n` feature as it is.

But how much would funding help? I'm not sure. Without quitting the day job, funding can only help with prioritization, not with getting extra time. So I personally suspect progress will be slow with or without funding...

**Comment by rauschma** [comment]
That makes sense. Thanks for the reply!
