### ISSUE TITLE
Is easily possible to implement support for multiline regex match?

### ISSUE THREAD

**Issue by evandrocoan** [trishume/syntect#53]
### Is easily possible to implement support for multiline regex match?

Currently on Sublime Text it is not possible to match multiple lines on an `match` clause.

1. https://github.com/SublimeTextIssues/Core/issues/1412
1. https://forum.sublimetext.com/t/how-to-match-a-function-call-spitted-across-multiples-lines-on-sublime-syntax/22392

**Comment by keith-hall** [comment]
I guess you could abuse the API and pass in multiple lines to the `parse_line` method but as this library aims to provide the same parsing experience as ST has, your question doesn't make much sense unless ST were to be updated to support it, and even then, how would it work? Pass the whole file to the `parse_line` method in one go? No good for large files. If you want to play around with it, you should fork this library, but I hope any changes that deviate so much from ST and abuse the API wouldn't get merged here.

**Comment by trishume** [comment]
Yah this totally breaks the idea of the Sublime Text parsing model. Not a good idea, I will never implement it and will not merge any pull request that does.

If you want to parse constructs that span multiple lines just `push` and `pop` constructs. If you want to highlight something on a previous line differently based on later lines, this isn't the library for you.

You're free to fork it if you want, but the API would totally change and performance would be abysmal.

**Comment by evandrocoan** [comment]
Then if I need something with performance and support for a push regex matching across several lines I need to implement a new API.

**Comment by trishume** [comment]
@evandrocoan because of the fundamental model of matching many regexes against the text and taking the earliest match, there is no way to support multi-line matching while having good performance. Running each regex on the entire file for every step will make performance O(n^2) in the file size.

In order to support highlighting something on earlier lines based on later lines with good performance you'll need an entirely different model. Almost none of syntect's parsing code will be useful to you. It would have to be a completely different library.

Why do you want to highlight earlier lines based on later lines? That's the only additional functionality this feature would get you, everything else can be done with the context stack.

**Comment by evandrocoan** [comment]
I want to be able to match/recognize crossed lines expression as functions calls like:
```
functionCall
(
    5,
    6
);
```
Here without seeing what is on the next line, a multiline regex cannot match/find out/determine whether `functionCall` is a function call.

As per see, multiline matches are not required on almost all cases. Therefore for performance, this new implementation should consider to enable multiline matching when explicitly required.

**Comment by trishume** [comment]
Fair enough, that is a real problem with the Sublime parsing model. But as I said it's out of scope for this library for API and performance reasons.

It would make the library unusable for text editors, which is an important use case for `syntect`, because text editors need to split the document into multiple buffers (in `syntect`'s case by line) for efficient editing, and there are currently no regex engines that are both fast and work on non-contigous buffers. It would also prevent various caching optimizations that ensure that the work when typing a character is proportional only to the size of the screen.

You may actually be able to approximate what you want by just passing your entire file to syntect as one "line" just one with `\n` characters in it. This will allow you to use multi-line regexes. It will just be slow, and I'm not sure how well existing syntaxes will work with it.

**Comment by evandrocoan** [comment]
Thanks for tips & time.
