### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [trishume/syntect#65]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by trishume** [comment]
Yah, I should probably do this at some point.

**Comment by robinst** [comment]
It looks like all the dependencies now also have versions that depend on serde 1.0: [plist](https://crates.io/crates/plist) and [bincode](https://crates.io/crates/bincode)

I can look at this if you want me to. I'm not sure what you want to do about this though: https://github.com/trishume/syntect/blob/c9b611f122a29238db66bcd11162558ad9cdb4b7/src/dumps.rs#L7-L9

The types from rustc-serialize are part of the API currently.

**Comment by trishume** [comment]
@robinst that might be a good idea. As far as I interpret my contract with Google, if I work on syntect any time in the next 3 months, it all belongs to Google since unlike my other projects, it is clearly in Google's business since it is used in a Google project. I'm not sure how that interacts with it being MIT licensed, but I'd rather play it safe.

 As for API/binary stability, meh. My policy is this: semver stability for the easy/html/core APIs and "meh, whatever" for everything else. I don't think anyone is using these in a way that will break except perhaps @Byron, and now that ping has given him warning. Although perhaps it would be a good idea to serialize a version number into the files before the rest of the contents so that at least the code could error on incompatibly files (and allow them to be regenerated perhaps) instead of just panic-ing or doing the wrong thing when de-serializing.

**Comment by Byron** [comment]
Thanks for the friendly warning :)! When I set things up for tokio-cassandara, I made it so that regenerating our syntaxes and themes would be easy. Whatever you come up with, I am sure I will be fine.

**Comment by robinst** [comment]
> if I work on syntect any time in the next 3 months, it all belongs to Google [...]

I would probably ask for clarification on that, normally companies are ok with it for open source projects and if you ask for permission first.

Thanks for that @Byron, that made it easier. I have made the changes now and will submit a PR soon.
