### ISSUE TITLE
Refactor to use an arena

### ISSUE THREAD

**Issue by trishume** [trishume/syntect#83]
This would be a large project, and may never happen, but the architecture would work much better with an arena of `Context`s instead of using `Rc<RefCell<>>` everywhere. Not only would the code be cleaner, but the lifetimes of `SyntaxDefinition` and `SyntaxSet` would be more correct, avoiding the footgun of dropping a `SyntaxSet` and keeping a cloned `SyntaxDefinition` that no longer has references to nested languages.

This would look something like using a `Vec<Context>` and indices everywhere.

It may also be easier to parallelize and make thread-safe, but that still requires extra work because of lazy regex compilation. See extensive discussion in #20.

**Comment by williamyaoh** [comment]
Re: lazy regex compilation: Just the change to an arena of some sort should be enough to make `SyntaxSet` be `Send`; a `Vec<RefCell<Context>>` would do the trick without needing to change the existing *logic* that much. This also opens up the possibility of storing `&RefCell<Context>` after linking syntaxes instead of indices, avoiding adding an extra layer of indirection on each `Context` link from the current implementation. 

It would be a bit too much to hope to combine `Send` with lazy regex compilation; that would pretty much require synchronizing thread-shared mutability on `Context`s, so using `Mutex`/`RwLock` or friends.

**Comment by williamyaoh** [comment]
Disregard that part about using `&RefCell` instead of numerical indices; it would be implementable, but would preclude a `Send` implementation. However, using a `Vec<RefCell<Context>>` to store a given `SyntaxSet`'s regexes + numerical indices as context links would still be enough to make it `Send`.

**Comment by trishume** [comment]
You're right, it would have the advantage of making it `Send`. I have a plan that could make it even `Sync` in #20: separate the compiled Regexes into a separate hash table and automatically pool those hash tables but access everything else between threads immutably. This is similar to what the Regex library does, I think I describe it more in #20.

**Comment by robinst** [comment]
Hey, looked into this a bit. I have some thoughts and wanted to check if they make sense:

Should we split the types so that "syntax definition read from yaml" and "linked syntax definition" are different types? Let's call the first one `SyntaxDefinition` and the second `SyntaxReference`. We could then have a `SyntaxSetBuilder` where you can add `SyntaxDefinition`, but when you call
`build`, you get a `SyntaxSet` (where all the contexts are linked). `SyntaxSet` and `SyntaxReference` is what you would pass to `ParseState`.

`SyntaxSet` and `SyntaxSetBuilder` would both be serializable. The advantage of having the first one would be that it would already be linked, so you could load it from the file and it would be ready to go. That would mean you'd need to have another pair of packdumps though (or maybe just include the `SyntaxSetBuilder` and if a library user cares, they can create their own dump).

I'm not sure how the `find_syntax_by` methods fit in with this, as they might also be useful for someone while building a syntax set.

**Comment by robinst** [comment]
This has been implemented in 3.0.0 :tada:: https://github.com/trishume/syntect/blob/master/CHANGELOG.md#version-30
