### ISSUE TITLE
Syntect fails to build when combined with serde

### ISSUE THREAD

**Issue by epage** [trishume/syntect#87]
I ran into this problem with cobalt.  I hacked around it by [disabling the default features I didn't need](https://github.com/cobalt-org/cobalt.rs/commit/3825a7e319f90a033eb20a3c967bb4d07cbdb355#diff-80398c5faae3c069e4e6aa2ed11b28c0).

Example error
```
error[E0308]: mismatched types
  --> /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-1.7.0/src/parsing/yaml_load.rs:90:34
   |
90 |         if let Ok(map) = get_key(h, "variables", |x| x.as_hash()) {
   |                                  ^ expected struct `std::collections::BTreeMap`, found struct `linked_hash_map::LinkedHashMap`
   |
   = note: expected type `&std::collections::BTreeMap<yaml_rust::Yaml, yaml_rust::Yaml>`
              found type `&linked_hash_map::LinkedHashMap<yaml_rust::Yaml, yaml_rust::Yaml>`
   = help: here are some functions which might fulfill your needs:
           - .hasher()
```

In case there is something weird we are doing with syntect
- [where its used](https://github.com/cobalt-org/cobalt.rs/blob/master/src/syntax_highlight.rs)
- [Cargo.toml](https://github.com/cobalt-org/cobalt.rs/blob/master/Cargo.toml)
- [lib.rs](https://github.com/cobalt-org/cobalt.rs/blob/master/src/lib.rs)

**Comment by epage** [comment]
This is being forked off of #84

**Comment by robinst** [comment]
I think the problem is this: https://github.com/dtolnay/serde-yaml/issues/33 which is caused by https://github.com/chyh1990/yaml-rust/issues/44

Basically, one of the dependencies of cobalt (serde-yaml) turns on the `preserve_order` feature, which changes what type `Hash` is in yaml-rust from `BTreeMap` to `LinkedHashMap`. Syntect expects to be compiled with the default features, which means using `BTreeMap`.

But I think we might be able to fix it by using the type alias instead of the concrete type instead. Let me try that.
