### ISSUE TITLE
How does it compare to Pygments?

### ISSUE THREAD

**Issue by kszucs** [trishume/syntect#99]
I'm especially curious about the lexer's performance.
There is also a [benchmarking suite](https://github.com/rubychan/shootout) containing other higlighters, might be easier to measure with.

**Comment by trishume** [comment]
It's a tough question. I expect syntect to be the same speed or faster than other syntax highlighting libraries at equivalent quality levels. However, syntect will often provide much higher quality levels than other highlighters, which may mean lower speeds. If you really care about speed, the higher quality might not matter to you, in which case you can either write a simpler syntax definition for syntect, or use a different highlighter.

For example, on jQuery based on the benchmark in the readme, syntect highlights JS at about 411kb/s. This is close to Pygments.rb and Rouge on the benchmark you link. However, compare [the 1400 line grammar Sublime uses for JS](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax) to [the one in Pygments](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/javascript.py?at=default&fileviewer=file-view-default), which is just 70 lines of code (the file contains many other grammars which make the file long). Sublime/syntect highlights all sorts of ES6 constructs and annotates the code with all sorts of things useful for fancy editor features and advanced highlighting.

If you want the fastest possible highlighting, just make everything black, or maybe just colour keywords. I agree it's useful to know how fast different highlighters are, but you also have to trade it off against quality because they all return different results.

**Comment by kszucs** [comment]
Actually I need lexers to extract code statistics (like `synstats` does) from 100GiBs of source code, which requires a fast lexer with base tokens available for most of the languages. 
IMHO Pygments [does a good job](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/token.py?at=default&fileviewer=file-view-default) with the defaults, but pretty slowly - sadly python is not shining in threading, so parallelizing is not really an option (although I can cythonize it). 

Syntect seems the closes one for what I want, but I need to create python bindings (where a C binding for syntect would be handy), and I'm not sure that it's worth the effort, but a good benchmark could convince me.
BTW where can I find the included grammars?

**Comment by trishume** [comment]
There is one company that is using syntect to process 80GB/hour of code for indexing and statistic purposes. But I think they might be using multiple beefy servers, I don't know. Syntect can be parallelized at the file level fairly easily, see https://github.com/trishume/syntect#parallelizing.

Doing some basic math it seems like an 8 core machine could process your 100GiB in 9 hours.

All the grammars are [here](https://github.com/sublimehq/Packages) but you can add any Sublime or `tmLanguage` (after converting) grammar, of which there are tons on the internet.

There's not much hope for syntect getting substantially faster, other than maybe #34. I've already done a lot of optimizing. The fundamental regex-based grammar model is the bottleneck now.

**Comment by trishume** [comment]
You can check out https://github.com/gjtorikian/syntect.rb for an example of binding it into a scripting language. Although if you want speed you probably want to do all the processing in Rust and just send the statistics back to Python.
